### ISSUE TITLE
Clean start, fresh install, "Nothing to Download!"

### ISSUE THREAD

**Issue by mstnorris** [DMarby/unsplash-downloader#13]
I thought maybe I'd changed something so I cloned the repository and started again, but all I get is "Nothing to Download!".

Maybe the unsplash API has changed.

**Comment by florisvaneck** [comment]
Running into exactly the same issue.

**Comment by nrutman** [comment]
Looks like Unsplash changed some of their markup (specifically the way they paginate) and the downloader is failing.

Specifically, [this code](https://github.com/DMarby/unsplash-downloader/blob/a8072e3449cb5c08d62daf0d0367ab38e4a33f38/index.js#L100-L106) in `getPageCount()` returns an empty result set. The logic needs to be updated to mirror the updated Unsplash markup.

**Comment by alandolsi** [comment]
Is there a solution for this probolem?

**Comment by iplus26** [comment]
Waiting for some one to update the code +1 
Or maybe I'll do it myself when I have time and then share with you guys~

**Comment by gpritiranjan** [comment]
Having the same issue. Any solution yet?

**Comment by benkaiser** [comment]
An alternative I wrote if anyone is interested is here: https://github.com/benkaiser/unsplash-downloader
You just need to issue an unsplash API key from here to use it https://unsplash.com/developers

**Comment by Mustyy** [comment]
@benkaiser Hey, quick question. When you say API key is that the same as application ID after signing up on api application for unsplash. I cant find my api consumer key

**Comment by benkaiser** [comment]
Yes that's what I mean, sorry haven't touched the project in a few months :)

**Comment by gpritiranjan** [comment]
@Mustyy, yes API Key and the Application ID are the same. So it does work and downloads the photos. But @benkaiser, since Unsplash gives 45 API request for an hour will the ID get blocked for too many API requests?

**Comment by benkaiser** [comment]
If I remember correctly, I put in a rate limit so it would do one per minute or something so that it wouldn't hit that limit.

**Comment by DMarby** [comment]
Hi, sorry for the late reply to this. Unsplash-downloader has been rewritten from scratch, and is now functional again.
