### ISSUE TITLE
Image download meta data fails at around 500

### ISSUE THREAD

**Issue by pocockn** [DMarby/unsplash-downloader#14]
After running unsplash-downloader from the command line using Mac I get this error.

Gathering image metadata... (536/1368)
Gathering image metadata... (537/1368)
An error occured, exiting.
__ASYNC_PROPS__ is not defined

**Comment by DMarby** [comment]
Hi, I've released version 1.0.1 which should fix this, please update it using NPM and try it out, let me know if it still doesn't work.
