### ISSUE TITLE
Can not download photos always "Gathering curated collections..."

### ISSUE THREAD

**Issue by chouti** [DMarby/unsplash-downloader#15]
I've installed from npm the latest version.
And after I run:
`unsplash-downloader -f ${MYPATH}`

it start displaying: Gathering curated collections...

and actually nothing downloaded. Am I missing something?

**Comment by DMarby** [comment]
Hi, 

Gathering curated collections shouldn't take more than a minute or so at most,
is nothing happening at all?

**Comment by DMarby** [comment]
Hi, 

Gathering curated collections shouldn't take more than a minute or so at most,
is nothing happening at all after that message is shown?

I've released a new version on NPM (1.0.2), could you try that and see if it works?
If it doesn't, could you set the environment variable NODE_ENV by doing:
```
NODE_ENV=development unsplash-downloader -f ${MYPATH}
```
and see if the downloader gets stuck on any page while trying to load it?
