### ISSUE TITLE
No metadata for All: true

### ISSUE THREAD

**Issue by CoenRispens** [DMarby/unsplash-downloader#5]
Hi,

when using the config.js, setting all: true, and changing the folder_path the App doesn't create a metadata file. Therefore when running the app again it seems to start downloading all of the pictures again instead of checking whether there are any new ones. 

By looking into findmissing.js it also seems that it doesn't account for changes into the folder_path to look for the location of the metadata file while the index.js seems to actually do this.

I hope this is useful to you, I have no java programming knowledge, so I'm afraid I can't submit the actual update for this!

Regards

**Comment by DMarby** [comment]
Hello,

I cannot reproduce this, metadata.json is created correctly on all my systems.
Are you sure that your paths are set correctly? 
In-case you are running this on windows I cannot be of much assistance, as this was never intended to be ran on it, and I do not use it with NodeJS myself.
