### ISSUE TITLE
Doesn't download, just finishes without downloading anything.

### ISSUE THREAD

**Issue by mstnorris** [DMarby/unsplash-downloader#7]
As the title suggests, running `node index.js` doesn't download any photos. The command just exits.

**Comment by realmat** [comment]
The same for me. I cannot download unsplash photos anymore.

**Comment by arturomazda** [comment]
Same for me :(

**Comment by chronologos** [comment]
I already made a pull request that fixes this bug, which is due to the unsplash website removing pagination and having a page that loads as it scrolls. The fork with the fixed code is in my repository.
