### ISSUE TITLE
Download does not continue

### ISSUE THREAD

**Issue by benkaiser** [DMarby/unsplash-downloader#9]
Steps to reproduce:
1. start the download with `node index`
2. cancel it at any point after it's downloaded some images
3. start it again with `node index`

What I expect to happen:
It recognizes that the files have already been downloaded up to some given point and continues from where it left off.

What actually happens:
It restarts the download and downloads all the already-downloaded comics again.

**Comment by mstnorris** [comment]
I get the same thing, this didn't happen previously.

**Comment by DMarby** [comment]
Hi, sorry for the super late reply, I recently rewrote unsplash-downloader from scratch, and it now picks up where it left off if interrupted.
